var Sequelize = require('sequelize');
var DB = require('./index');

const GREFERENCIAPORBODEGA = DB.define('GREFERENCIAPORBODEGA', {
  GLBCodigoReferenciaReferenciaPorBodega: Sequelize.STRING,
  GLBCodigoBodegaReferenciaPorBodega: Sequelize.STRING,
  GLBUltimaFechaCompraReferenciaPorBodega: Sequelize.STRING,
  GLBUltimaFechaVentaReferenciaPorBodega: Sequelize.STRING,
  GLBEntradasPeriodoPesosReferenciaPorBodega: Sequelize.DECIMAL,
  GLBEntradasAcumPesosReferenciaPorBodega: Sequelize.DECIMAL,
  GLBEntradasPeriodoUnidadReferenciaPorBodega: Sequelize.DECIMAL,
  GLBEntradasAcumUnidadReferenciaPorBodega: Sequelize.DECIMAL,
  GLBSalidasPeriodoPesosReferenciaPorBodega: Sequelize.DECIMAL,
  GLBSalidasAcumPesosReferenciaPorBodega: sequelize.DECIMAL,
  GLBSalidasPeriodoUnidadReferenciaPorBodega: sequelize.DECIMAL,
  GLBSalidasAcumUnidadReferenciaPorBodega: sequelize.DECIMAL,
  GLBOtrasEntradasPeriodoPesosReferenciaPorBodega: sequelize.DECIMAL,
  GLBOtrasEntradasAcumPesosReferenciaPorBodega: sequelize.DECIMAL,
  GLBOtrasEntradasPeriodoUnidadReferenciaPorBodega: sequelize.DECIMAL,
  GLBOtrasEntradasAcumUnidadReferenciaPorBodega: sequelize.DECIMAL,
  GLBOtrasSalidasPeriodoPesosReferenciaPorBodega: sequelize.DECIMAL,
  GLBOtrasSalidasAcumPesosReferenciaPorBodega: sequelize.DECIMAL,
  GLBOtrasSalidasPeriodoUnidadReferenciaPorBodega: sequelize.DECIMAL,
  GLBOtrasSalidasAcumUnidadReferenciaPorBodega: sequelize.DECIMAL,
  GLBAjustesPeriodoPesosReferenciaPorBodega: sequelize.DECIMAL,
  GLBAjustesAcumPesosReferenciaPorBodega: sequelize.DECIMAL,
  GLBAjustesPeriodoUnidadReferenciaPorBodega: sequelize.DECIMAL,
  GLBAjustesAcumUnidadReferenciaPorBodega: sequelize.DECIMAL,
  GLBExistenciaInicialReferenciaPorBodega: sequelize.DECIMAL,
  GLBExistenciaReferenciaPorBodega: sequelize.DECIMAL,
  GLBExistenciaVirtualReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoPromedioInicialReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoPromedioIncialAjustadoReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoPromedioReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoPromedioAjustadoReferenciaPorBodega: sequelize.DECIMAL,
  GLBUltimoCostoInicialReferenciaPorBodega: sequelize.DECIMAL,
  GLBUltimoCostoInicialAjustadoReferenciaPorBodega: sequelize.DECIMAL,
  GLBUltimoCostoReferenciaPorBodega: sequelize.DECIMAL,
  GLBUltimoCostoAjustadoReferenciaPorBodega: sequelize.DECIMAL,
  GLBContadorVentasReferenciaPorBodega: sequelize.DECIMAL,
  GLBContadorVentasAnoReferenciaPorBodega: sequelize.DECIMAL,
  GLBIndicePeriodoReferenciaPorBodega: sequelize.DECIMAL,
  GLBIndiceAcumuladoReferenciaPorBodega: sequelize.DECIMAL,
  GLBCuentaInventariosReferenciaPorBodega: sequelize.STRING,
  GLBCuentaCostoProduccionReferenciaPorBodega: sequelize.STRING,
  GLBCuentaInventarioProcesoReferenciaPorBodega: sequelize.STRING,
  GLBCuentaInventarioProdTerminadoReferenciaPorBodega: sequelize.STRING,
  GLBCostoNIFFPromedioInicialReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoNIFFPromedioIncialAjustadoReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoNIFFPromedioReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoNIFFPromedioAjustadoReferenciaPorBodega: sequelize.DECIMAL,
  GLBUltimoCostoNIFFInicialReferenciaPorBodega: sequelize.DECIMAL,
  GLBUltimoCostoNIFFInicialAjustadoReferenciaPorBodega: sequelize.DECIMAL,
  GLBUltimoCostoNIFFReferenciaPorBodega: sequelize.DECIMAL,
  GLBUltimoCostoNIFFAjustadoReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoPEPSInicialFiscalReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoPEPSActualFiscalReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoUEPSInicialFiscalReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoUEPSActualFiscalReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoPEPSInicialNIIFReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoPEPSActualNIIFReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoUEPSInicialNIIFReferenciaPorBodega: sequelize.DECIMAL,
  GLBCostoUEPSActualNIIFReferenciaPorBodega: sequelize.DECIMAL
  },
  {
    indexes:[{primary: true, name: "PK_GREFERENCIAPORBODEGA", fields: ["GLBCodigoReferenciaReferenciaPorBodega", "GLBCodigoBodegaReferenciaPorBodega"]}],
    timestamps: false,
    freezeTableName: true,
    schema: 'dbo'
  }
);

GREFERENCIAPORBODEGA.removeAttribute('id');

module.exports = GREFERENCIAPORBODEGA;
